# Use an official Python image as a base
FROM python:alpine3.21

# Set the working directory in the container
WORKDIR /app

# Create non-root user
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app files into the container
COPY app /app

# Switch to non-root user
# USER appuser

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["python", "app.py"]
